apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: mysql
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-09-30T10:47:38Z"
  labels:
    app: mysql
    app.kubernetes.io/managed-by: Helm
    chart: mysql-1.6.9
    heritage: Helm
    release: mysql
  name: mysql
  namespace: default
  resourceVersion: "42536"
  uid: 2d9864b6-43e0-4996-ae50-c07f363c8f0a
spec:
  volumeName: mysql-pv
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
status:
  phase: Pending
