apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON {{ .Values.postgresqlDatabase }}.* TO '{{ .Values.postgresqlUser }}'@'%';
    Flush Privileges;