apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgresqlPVName }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.postgresqlStorageClassName }}
  hostPath:
    path: "/data/postgresql"