apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresqlPVCName }}
spec:
  storageClassName: {{ .Values.postgresqlStorageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi