apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  postgresql-root-password: {{ .Values.postgresqlRootPassword | b64enc | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresqlPassword | b64enc | quote }}