apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.wordpressPVName }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.wordpressStorageClassName }}
  hostPath:
    path: "/data/wordpress"