apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysqlPVCName }}
spec:
  storageClassName: {{ .Values.mysqlStorageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi