apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.wordpressPVCName }}
spec:
  storageClassName: {{ .Values.wordpressStorageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi